[package]
name = "rustserver"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1.0.208", features = ["derive"]}
serde_json = "1.0.61"
actix-web = "4"
log = "0.4.22"
env_logger = "0.11.5"
rustagent = "0.1.1"
